steps:
- name: 'fortifydocker/fortify-ci-tools:latest'
  entrypoint: bash
  args: 
    - -c
    - |
       #uncomment below command if scancentral server is expecting a client auth token
       #echo client_auth_token=XXXXXXX > /opt/Fortify/ScanCentral/Core/config/client.properties
       scancentral -url $$FORTIFY_SC_URL start --build-tool none -uptoken $$FORTIFY_CI_TOKEN -upload --application $$APP_NAME --application-version $$APP_VERSION
  env:
    - 'FORTIFY_SC_URL=${_SC_URL}'
    - 'FORTIFY_CI_TOKEN=${_SC_CI_TOKEN}'
    - 'APP_NAME=sample'
    - 'APP_VERSION=eightball'

timeout: 2400s